#Install dependencies on the host
- name: Install apt packages
  become: yes
  apt:
          name: ['python-pip', 'git', 'apache2', 're', 'erlang', 'npm', 'nodejs', 'rebar']
          state: latest
          update_cache: yes
  #when: ansible_distribution == "Ubuntu"
#sudo apt-get update; sudo apt-get update python-pip

- name: Install pip packages
  become: yes
  pip:
          name: ['pip', 'openstacksdk', 'tweepy', 'nltk', 'screen', 'apscheduler', 'geopy', 'textblob']
          state: latest

- name: Set authorized key on instances
  authorized_key:
          user: ubuntu
          state: present
          key: "{{ lookup('file', item) }}"
  with_fileglob: "~/.ssh/id_rsa.pub'"

- name: Add server Configuration in instance
  become: yes
  lineinfile:
          path: /etc/environment
          state: present
          line: "http_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nhttps_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nftp_proxy=\"http://wwwproxy.unimelb.edu.au:8000\"\nno_proxy=localhost,127.0.0.1,127.0.1.1,ubuntu,{{ host_name }}.novalocal,{{ host_name }},{{ host_IP }}"

- name: download couchdb from git
  become: yes
  git:
          repo: "https://git-wip-us.apache.org/repos/asf/couchdb.git"
          dest: "{{ couchdb_install_dir }}"
          accept_hostkey: yes
          version: "{{ couchdb_version }}"

- name: Install grunt globally
  npm: "name=grunt-cli global=yes"
  become: yes

- name: Run configure
  become: yes
  shell: "./configure chdir={{ couchdb_install_dir }}"

- name: Run make clean
  become: yes
  shell: "make clean chdir={{ couchdb_install_dir }}"

- name: Tee to /etc/apt/sources.list
  become: yes
  shell: "echo \"deb https://apache.bintray.com/couchdb-deb bionic main\" | sudo tee -a /etc/apt/sources.list"

- name: Add key
  become: yes
  shell: "curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc | sudo apt-key add -"

- name: Install couchdb
  become: yes
  apt:
          name: ['couchdb']
          update_cache: yes
          state: latest

- name: Install the sysv script to run CouchDB as a service
  copy:
          src: "couchdb"
          dest: "/etc/init.d/couchdb"
          mode: "0755"

- name: Start CouchDB and enabl it at boot time
  service:
          name: "couchdb"
          state: started
          enabled: yes

- name: Update vm.args file
  template:
          src: "vm.args.j2"
          dest: "/opt/couchdb/etc/vm.args"

- name: Update the .ini files
  become: yes
  copy:
          src: "~/COMP90024_Project/nectar/etc_files/{{ item }}"
          dest: "/opt/couchdb/etc/{{ item }}"
  with_items:
          - "local.ini"
          - "local.d/10-admins.ini"

- name: Update local.ini on all servers except server1
  become: yes
  lineinfile:
          path: "/opt/couchdb/etc/local.ini"
          regexp: "^[chttpd]\nport = 5984\nbind_address = 0\.0\.0\.0"
          line: "[chttpd]"
  when: inventory_hostname != "{{ groups.servers134[0] }}"

- name: update local.d/10-admins.ini
  become: yes
  lineinfile:
          path: "/opt/couchdb/etc/local.d/10-admins.ini"
          regexp: "^[chttpd]\nbind_address = 0\.0\.0\.0"
          line: "[chttpd]"
  when: inventory_hostname != "{{ groups.servers134[0] }}"

- name: Enable the cluster
  uri:
          status_code: 201
          HEADER_Content-Type: "application/json"
          user: "admin"
          password: "admin"
          method: POST
          body_format: json
          url: "http://127.0.0.1:5984/_cluster_setup"
          body: "'{\"action\":\"enable_cluster\",\"bind_address\":\"0.0.0.0\",\"username\":\"admin\",\"password\":\"admin\",\"node_count\":\"3\"}'"

- name: Add nodes to the cluster
  uri:
          status_code: 201,409
          HEADER_Content-Type: "application/json"
          user: "admin"
          password: "admin"
          method: POST
          force_basic_auth: yes
          body_format: json
          url: "http://127.0.0.1:5984/_cluster_setup"
          body: "'{\"action\":\"add_node\",\"username\":\"admin\",\"password\":\"admin\",\"host\":\"{{ host_IP }}\",\"port\":5984}'"
  when: inventory_hostname == "{{ groups.servers134[0] }}"

- name: Finish the cluster
  uri:
          status_code: 201
          HEADER_Content-Type: "application/json"
          user: "admin"
          password: "amdin"
          method: POST
          force_basic_auth: yes
          url: "http://127.0.0.1:5984/_cluster_setup"
          body_format: json
          body: "'{\"action\":\"finish_cluster\"}'"
  when: inventory_hostname == "{{ groups.servers134[0] }}"
