#Team 46: (Advait Mangesh Deshpande (1005024), Ansh Juneja (1027339), Saransh Srivastava (1031073), Siyu Biyan (984002), Waqar Ul Islam (1065823));
##Cities Analysed: Adelaide, Brisbane, Canberra, Geelong, Gold Coast, Melbourne, Newcastle, Perth, Sydney, Townsville
#Create instance on NeCTAR
- name: Create instance1
  os_server:
          name: "{{ instance_name1 }}"
          image: "{{ instance_image }}"
          key_name: "{{ instance_key_name }}"
          flavor: "{{ instance_flavor }}"
          availability_zone: "{{ availability_zone }}"
          security_groups: "{{ sg_name }}"
          volumes: "{{ os_vol_id1 }}"
          auto_floating_ip: yes
          wait: yes
          timeout: 600
          state: present
  register: os_instance1

- name: Create instance2
  os_server:
          name: "{{ instance_name2 }}"
          image: "{{ instance_image }}"
          key_name: "{{ instance_key_name }}"
          flavor: "{{ instance_flavor }}"
          availability_zone: "{{ availability_zone }}"
          security_groups: "{{ sg_name }}"
          volumes: "{{ os_vol_id2 }}"
          auto_floating_ip: yes
          wait: yes
          timeout: 600
          state: present
  register: os_instance2
  
- name: Create instance3
  os_server:
          name: "{{ instance_name3 }}"
          image: "{{ instance_image }}"
          key_name: "{{ instance_key_name }}"
          flavor: "{{ instance_flavor }}"
          availability_zone: "{{ availability_zone }}"
          security_groups: "{{ sg_name }}"
          volumes: "{{ os_vol_id3 }}"
          auto_floating_ip: yes
          wait: yes
          timeout: 600
          state: present
  register: os_instance3
  
- name: Create instance4
  os_server:
          name: "{{ instance_name4 }}"
          image: "{{ instance_image }}"
          key_name: "{{ instance_key_name }}"
          flavor: "{{ instance_flavor }}"
          availability_zone: "{{ availability_zone }}"
          security_groups: "{{ sg_name }}"
          volumes: "{{ os_vol_id4 }}"
          auto_floating_ip: yes
          wait: yes
          timeout: 600
          state: present
  register: os_instance4
  
- debug:
        msg: "instance1 has been created with IP address {{ os_instance1.openstack.public_v4 }}"
  when: os_instance1.openstack is defined

- debug:
        msg: "instance2 has been created with IP address {{ os_instance2.openstack.public_v4 }}"
  when: os_instance2.openstack is defined
  
- debug:
        msg: "instance3 has been created with IP address {{ os_instance3.openstack.public_v4 }}"
  when: os_instance3.openstack is defined
 
- debug:
        msg: "instance4 has been created with IP address {{ os_instance4.openstack.public_v4 }}"
  when: os_instance4.openstack is defined
